#r @"/home/vscode/.nuget/packages/akka.serialization.hyperion/1.4.36/lib/netstandard2.0/Akka.Serialization.Hyperion.dll"
#r @"/home/vscode/.nuget/packages/akka.streams/1.4.36/lib/netstandard2.0/Akka.Streams.dll"
#r @"/home/vscode/.nuget/packages/akka/1.4.36/lib/netstandard2.0/Akka.dll"
#r @"/home/vscode/.nuget/packages/akkling.streams/0.12.0/lib/netstandard2.0/Akkling.Streams.dll"
#r @"/home/vscode/.nuget/packages/akkling/0.12.0/lib/netstandard2.0/Akkling.dll"
#r @"/home/vscode/.nuget/packages/fsharp.data/4.2.8/lib/netstandard2.0/FSharp.Data.dll"
#r @"/home/vscode/.nuget/packages/fshttp/9.0.4/lib/net6.0/FsHttp.dll"
#r @"/home/vscode/.nuget/packages/google.protobuf/3.20.0/lib/net5.0/Google.Protobuf.dll"
#r @"/home/vscode/.nuget/packages/hyperion/0.12.2/lib/netstandard2.0/Hyperion.dll"
#r @"/home/vscode/.nuget/packages/microsoft.bcl.asyncinterfaces/6.0.0/lib/netstandard2.1/Microsoft.Bcl.AsyncInterfaces.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/Microsoft.CSharp.dll"
#r @"/home/vscode/.nuget/packages/microsoft.extensions.objectpool/6.0.3/lib/net6.0/Microsoft.Extensions.ObjectPool.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/Microsoft.VisualBasic.Core.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/Microsoft.VisualBasic.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/Microsoft.Win32.Primitives.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/Microsoft.Win32.Registry.dll"
#r @"/home/vscode/.nuget/packages/microsoft.win32.systemevents/6.0.0/lib/net6.0/Microsoft.Win32.SystemEvents.dll"
#r @"/home/vscode/.nuget/packages/newtonsoft.json/13.0.1/lib/netstandard2.0/Newtonsoft.Json.dll"
#r @"/home/vscode/.nuget/packages/reactive.streams/1.0.2/lib/netstandard1.0/Reactive.Streams.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.AppContext.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Buffers.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Collections.Concurrent.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Collections.Immutable.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Collections.NonGeneric.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Collections.Specialized.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Collections.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.ComponentModel.Annotations.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.ComponentModel.DataAnnotations.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.ComponentModel.EventBasedAsync.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.ComponentModel.Primitives.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.ComponentModel.TypeConverter.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.ComponentModel.dll"
#r @"/home/vscode/.nuget/packages/system.configuration.configurationmanager/6.0.0/lib/net6.0/System.Configuration.ConfigurationManager.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Configuration.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Console.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Core.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Data.Common.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Data.DataSetExtensions.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Data.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Diagnostics.Contracts.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Diagnostics.Debug.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Diagnostics.DiagnosticSource.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Diagnostics.FileVersionInfo.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Diagnostics.Process.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Diagnostics.StackTrace.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Diagnostics.TextWriterTraceListener.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Diagnostics.Tools.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Diagnostics.TraceSource.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Diagnostics.Tracing.dll"
#r @"/home/vscode/.nuget/packages/system.drawing.common/6.0.0/lib/net6.0/System.Drawing.Common.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Drawing.Primitives.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Drawing.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Dynamic.Runtime.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Formats.Asn1.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Globalization.Calendars.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Globalization.Extensions.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Globalization.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.IO.Compression.Brotli.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.IO.Compression.FileSystem.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.IO.Compression.ZipFile.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.IO.Compression.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.IO.FileSystem.AccessControl.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.IO.FileSystem.DriveInfo.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.IO.FileSystem.Primitives.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.IO.FileSystem.Watcher.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.IO.FileSystem.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.IO.IsolatedStorage.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.IO.MemoryMappedFiles.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.IO.Pipes.AccessControl.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.IO.Pipes.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.IO.UnmanagedMemoryStream.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.IO.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Linq.Expressions.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Linq.Parallel.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Linq.Queryable.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Linq.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Memory.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Net.Http.Json.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Net.Http.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Net.HttpListener.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Net.Mail.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Net.NameResolution.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Net.NetworkInformation.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Net.Ping.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Net.Primitives.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Net.Requests.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Net.Security.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Net.ServicePoint.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Net.Sockets.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Net.WebClient.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Net.WebHeaderCollection.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Net.WebProxy.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Net.WebSockets.Client.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Net.WebSockets.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Net.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Numerics.Vectors.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Numerics.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.ObjectModel.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Reflection.DispatchProxy.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Reflection.Emit.ILGeneration.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Reflection.Emit.Lightweight.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Reflection.Emit.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Reflection.Extensions.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Reflection.Metadata.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Reflection.Primitives.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Reflection.TypeExtensions.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Reflection.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Resources.Reader.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Resources.ResourceManager.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Resources.Writer.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Runtime.CompilerServices.Unsafe.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Runtime.CompilerServices.VisualC.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Runtime.Extensions.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Runtime.Handles.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Runtime.InteropServices.RuntimeInformation.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Runtime.InteropServices.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Runtime.Intrinsics.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Runtime.Loader.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Runtime.Numerics.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Runtime.Serialization.Formatters.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Runtime.Serialization.Json.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Runtime.Serialization.Primitives.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Runtime.Serialization.Xml.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Runtime.Serialization.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Runtime.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Security.AccessControl.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Security.Claims.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Security.Cryptography.Algorithms.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Security.Cryptography.Cng.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Security.Cryptography.Csp.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Security.Cryptography.Encoding.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Security.Cryptography.OpenSsl.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Security.Cryptography.Primitives.dll"
#r @"/home/vscode/.nuget/packages/system.security.cryptography.protecteddata/6.0.0/lib/net6.0/System.Security.Cryptography.ProtectedData.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Security.Cryptography.X509Certificates.dll"
#r @"/home/vscode/.nuget/packages/system.security.permissions/6.0.0/lib/net6.0/System.Security.Permissions.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Security.Principal.Windows.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Security.Principal.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Security.SecureString.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Security.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.ServiceModel.Web.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.ServiceProcess.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Text.Encoding.CodePages.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Text.Encoding.Extensions.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Text.Encoding.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Text.Encodings.Web.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Text.Json.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Text.RegularExpressions.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Threading.Channels.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Threading.Overlapped.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Threading.Tasks.Dataflow.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Threading.Tasks.Extensions.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Threading.Tasks.Parallel.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Threading.Tasks.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Threading.Thread.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Threading.ThreadPool.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Threading.Timer.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Threading.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Transactions.Local.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Transactions.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.ValueTuple.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Web.HttpUtility.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Web.dll"
#r @"/home/vscode/.nuget/packages/system.windows.extensions/6.0.0/lib/net6.0/System.Windows.Extensions.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Windows.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Xml.Linq.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Xml.ReaderWriter.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Xml.Serialization.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Xml.XDocument.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Xml.XPath.XDocument.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Xml.XPath.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Xml.XmlDocument.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Xml.XmlSerializer.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.Xml.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/System.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/WindowsBase.dll"
#r @"/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.2/ref/net6.0/netstandard.dll"
#load @"/workspaces/gerrit2/src/Server/Program.fs"

open Server.App.Domain
open FsHttp
open System

module Async = 
    let map f x = async{
        let! v = x
        return f v
    }
    let bind f x = async {
        let! v = x
        return! f v
    }

let skipLine (s:string) = 
    let ln = s.IndexOf(Environment.NewLine)
    s.Substring(ln)

let getChanges url token =

    http {
            GET url
            Authorization token
        }
        |> Request.sendAsync
        |> Async.bind Response.toTextAsync
        |> Async.map skipLine
        |> Async.map Gerrit.Parse

let items = 
    getChanges 
        @"https://review.gerrithub.io/a/changes/?q=p:OnurGumus/Bindrake2"
        "Basic T251ckd1bXVzOis2NFNTQmpTTGtlN3N3c0NPMlBhZW44NnByamhvTUkvUUxMRDZPY0tKUQ=="
    |> Async.RunSynchronously

let first:Gerrit.Root = items[0]